name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  Deploy:
    name: Deploy
    runs-on: macOS-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
      - name: Prepare Dependencies
        env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            set -o pipefail
            carthage version
            carthage bootstrap --use-xcframeworks

      - name: Generate Docs
        run: ./CI/publish-docs.sh

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Build Carthage Binary
        run: |
            ./CI/publish-carthage.sh;
      - name: Upload Carthage Binary
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'VirgilCryptoWrapper.xcframework.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Cocoapods
        run: ./CI/publish-cocoapods.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

